BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `player` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`gamecount`	INTEGER NOT NULL,
	`wincount`	INTEGER NOT NULL
);
COMMIT;
